name: Build Docker Image on Push

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and Optionally Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub (ถ้าต้องการ push image)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and tag Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            phatysd/test-gitaction:latest
            phatysd/test-gitaction:${{ github.sha }}
      - name: Image details
        if: ${{ steps.build-image.outputs.digest }}
        run: |
            echo "Digest: ${{ steps.build-image.outputs.digest }}"
            echo "Tags: ${{ steps.build-image.outputs.tags }}"
